#define RF_RESET       GPIO_PIN(PORT_A, 0)
#define PERIPH_EN      GPIO_PIN(PORT_A, 1)
#define ADC_OSRAM      GPIO_PIN(PORT_A, 4)
#define ADC_VCAP       GPIO_PIN(PORT_A, 5)
#define ADC_VSOLAR     GPIO_PIN(PORT_A, 6)
#define ADC_5V         GPIO_PIN(PORT_A, 7)
#define RF_EN          GPIO_PIN(PORT_A, 8)
#define RF_MISO        GPIO_PIN(PORT_A, 11)
#define RF_MOSI        GPIO_PIN(PORT_A, 12)
#define EXTINT2_B      GPIO_PIN(PORT_A, 13)
#define EXTINT1_B      GPIO_PIN(PORT_A, 14)
#define SDI12_OE       GPIO_PIN(PORT_A, 15)

#define RF_DIO0        GPIO_PIN(PORT_B, 0)
#define RF_DIO1        GPIO_PIN(PORT_B, 1)
#define RF_DIO2        GPIO_PIN(PORT_B, 2)
#define RF_SCK         GPIO_PIN(PORT_B, 3)
#define EXTINT2        GPIO_PIN(PORT_B, 4)
#define THEFT_DETECT   GPIO_PIN(PORT_B, 5)
#define SUP12V_EN      GPIO_PIN(PORT_B, 8)
#define EXTINT1        GPIO_PIN(PORT_B, 9)
#define REED_RAIN      GPIO_PIN(PORT_B, 12)
#define ADC_RS1        GPIO_PIN(PORT_B, 13)
#define EXTINT_CTRL    GPIO_PIN(PORT_B, 14)
#define ADC_RS3        GPIO_PIN(PORT_B, 15)

#define RF_NSS         GPIO_PIN(PORT_C, 13)

#define SHT3X_PARAM_I2C_DEV     (I2C_DEV(0))
#define SHT3X_PARAM_I2C_ADDR    (SHT3X_I2C_ADDR_1)
#define SHT3X_PARAM_I2C_ADDR_1  (SHT3X_I2C_ADDR_2)
#define SHT3X_PARAM_MODE        (SHT3X_SINGLE_SHOT)
#define SHT3X_PARAM_REPEAT      (SHT3X_HIGH)

#define BMP180_PARAM_I2C_DEV         I2C_DEV(0)
#define BMP180_PARAM_I2C_ADDR        (0x76)
#define BMP180_PARAM_OVERSAMPLING    BMP180_ULTRALOWPOWER

#define LIS2DH12_PARAM_I2C          I2C_DEV(0)
#define LIS2DH12_PARAM_ADDR         (0x18)